name: Build EXE with PyInstaller

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: 체크아웃
      uses: actions/checkout@v4

    - name: Python 설정
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: 의존성 설치
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller numpy matplotlib opencv-python pygame dlib PyQt6

    - name: EXE 빌드
      run: |
        pyinstaller --noconfirm --onefile --windowed main.py

    - name: 빌드 결과 업로드
      uses: actions/upload-artifact@v3
      with:
        name: built-exe
        path: dist/main.exe
